[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "gamemaster"
version = "0.1.0"
description = "AgentCore Runtime Application using Strands SDK"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aws-opentelemetry-distro",
    "bedrock-agentcore >= 1.9.1",
    "boto3>=1.43.56",
    "httpx>=0.28.1",
    "mcp-proxy-for-aws>=1.6.4",
    "strands-agents >= 1.15.0",
]

[tool.hatch.build.targets.wheel]
packages = ["."]
